non_food = [
    "plate",
    "bowl",
    "bottle",
    "mug",
    "glass",
    "cup",
    "saucer",
    "spoon",
    "fork",
    "knife",
    "chopsticks",
    "straw",
    "tongs",
    "cutting board",
    "cooking pot",
    "frying pan",
    "skillet",
    "saucepan",
    "baking dish",
    "oven tray",
    "grater",
    "peeler",
    "whisk",
    "rolling pin",
    "ladle",
    "spatula",
    "colander",
    "measuring cup",
    "measuring spoon",
    "mortar and pestle",
    "blender",
    "food processor",
    "juicer",
    "griddle",
    "wok",
    "toaster",
    "salt shaker",
    "pepper grinder",
    "jar",
    "tablecloth",
    "napkin",
    "coaster",
    "tray",
    "placemat",
    "candle",
    "flower vase",
    "table centerpiece",
    "serving tray",
    "basket",
    "wooden board",
    "mixing bowl",
    "baking sheet",
    "baking rack",
    "piping bag",
    "cake stand",
    "serving stand",
    "box",
    "newspaper",
    "paper bag",
    "plastic bag",
    "foam",
    "clamshell container",
    "aluminum foil wrap",
    "paper wrapper",
    "disposable coffee lid",
    "straw",
    "condiment sachets",
    "chopstick",
    "towel",
    "packets",
    "menu",
    "stand",
    "smartphone",
    "coin",
    "keys",
    "wallet",
    "sunglasses",
    "watch",
    "earbuds",
    "carrier",
]
